import React, { useState } from 'react'
import { motion } from 'framer-motion'
import {
    MessageSquare,
    Calendar,
    Copy,
    Send,
    RefreshCw,
    CheckCircle,
    AlertCircle,
    Clock
} from 'lucide-react'

const containerVariants = {
    hidden: { opacity: 0 },
    visible: { opacity: 1, transition: { staggerChildren: 0.1 } }
}

const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0 }
}

export default function Standup() {
    const [copied, setCopied] = useState(false)

    const today = new Date().toLocaleDateString('en-US', {
        weekday: 'long',
        month: 'long',
        day: 'numeric'
    })

    const standup = {
        completed: [
            { key: 'PROJ-101', title: 'User authentication flow', assignee: 'Sarah Chen', points: 5 },
            { key: 'PROJ-102', title: 'Dashboard redesign', assignee: 'John Davis', points: 8 },
        ],
        inProgress: [
            { key: 'PROJ-103', title: 'API optimization', assignee: 'Mike Wilson', points: 5, progress: 60 },
            { key: 'PROJ-104', title: 'Payment integration', assignee: 'Lisa Kim', points: 8, progress: 40 },
        ],
        blockers: [
            { key: 'PROJ-105', title: 'Email notifications', reason: 'Waiting for API credentials', days: 3 },
        ],
    }

    const handleCopy = () => {
        const text = generateStandupText()
        navigator.clipboard.writeText(text)
        setCopied(true)
        setTimeout(() => setCopied(false), 2000)
    }

    const generateStandupText = () => {
        return `📋 Daily Standup - ${today}
Sprint 42 | Day 5 of 10

✅ COMPLETED YESTERDAY
${standup.completed.map(i => `• ${i.key}: ${i.title} (${i.assignee})`).join('\n')}

🔄 IN PROGRESS TODAY
${standup.inProgress.map(i => `• ${i.key}: ${i.title} - ${i.progress}% (${i.assignee})`).join('\n')}

🚫 BLOCKERS
${standup.blockers.length ? standup.blockers.map(i => `• ${i.key}: ${i.reason} (${i.days} days)`).join('\n') : 'No blockers! 🎉'}

---
Generated by Sprint Strategist 🏎️`
    }

    return (
        <motion.div
            variants={containerVariants}
            initial="hidden"
            animate="visible"
            className="max-w-4xl mx-auto space-y-6"
        >
            {/* Header */}
            <motion.div variants={itemVariants} className="flex items-center justify-between">
                <div>
                    <h1 className="text-3xl font-display font-bold gradient-text">Daily Standup</h1>
                    <p className="text-text-muted mt-1 flex items-center gap-2">
                        <Calendar className="w-4 h-4" />
                        {today}
                    </p>
                </div>
                <div className="flex gap-2">
                    <motion.button
                        className="btn-secondary"
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                    >
                        <RefreshCw className="w-4 h-4 mr-2" />
                        Regenerate
                    </motion.button>
                    <motion.button
                        className="btn-glow"
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={handleCopy}
                    >
                        {copied ? <CheckCircle className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                        {copied ? 'Copied!' : 'Copy to Clipboard'}
                    </motion.button>
                </div>
            </motion.div>

            {/* Standup Card */}
            <motion.div variants={itemVariants} className="glass-card p-8">
                {/* Completed */}
                <div className="mb-8">
                    <h3 className="text-lg font-semibold mb-4 flex items-center gap-2 text-success">
                        <CheckCircle className="w-5 h-5" />
                        Completed Yesterday
                    </h3>
                    <div className="space-y-3">
                        {standup.completed.map((item, index) => (
                            <motion.div
                                key={item.key}
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: index * 0.1 }}
                                className="flex items-center gap-4 p-4 rounded-xl bg-success/10 border border-success/20"
                            >
                                <CheckCircle className="w-5 h-5 text-success" />
                                <span className="text-accent font-mono text-sm">{item.key}</span>
                                <span className="flex-1">{item.title}</span>
                                <span className="text-text-muted text-sm">{item.assignee}</span>
                                <span className="badge-success">{item.points} pts</span>
                            </motion.div>
                        ))}
                    </div>
                </div>

                {/* In Progress */}
                <div className="mb-8">
                    <h3 className="text-lg font-semibold mb-4 flex items-center gap-2 text-accent">
                        <Clock className="w-5 h-5" />
                        In Progress Today
                    </h3>
                    <div className="space-y-3">
                        {standup.inProgress.map((item, index) => (
                            <motion.div
                                key={item.key}
                                initial={{ opacity: 0, x: -20 }}
                                animate={{ opacity: 1, x: 0 }}
                                transition={{ delay: index * 0.1 + 0.2 }}
                                className="p-4 rounded-xl bg-dark-700/50 border border-dark-500"
                            >
                                <div className="flex items-center gap-4 mb-3">
                                    <Clock className="w-5 h-5 text-accent" />
                                    <span className="text-accent font-mono text-sm">{item.key}</span>
                                    <span className="flex-1">{item.title}</span>
                                    <span className="text-text-muted text-sm">{item.assignee}</span>
                                    <span className="badge-accent">{item.points} pts</span>
                                </div>
                                <div className="flex items-center gap-4">
                                    <div className="flex-1 h-2 bg-dark-600 rounded-full overflow-hidden">
                                        <motion.div
                                            className="h-full bg-accent rounded-full"
                                            initial={{ width: 0 }}
                                            animate={{ width: `${item.progress}%` }}
                                            transition={{ duration: 1 }}
                                        />
                                    </div>
                                    <span className="text-sm text-accent">{item.progress}%</span>
                                </div>
                            </motion.div>
                        ))}
                    </div>
                </div>

                {/* Blockers */}
                <div>
                    <h3 className="text-lg font-semibold mb-4 flex items-center gap-2 text-danger">
                        <AlertCircle className="w-5 h-5" />
                        Blockers
                    </h3>
                    {standup.blockers.length === 0 ? (
                        <div className="text-center py-8 text-success">
                            <span className="text-4xl">🎉</span>
                            <p className="mt-2">No blockers today!</p>
                        </div>
                    ) : (
                        <div className="space-y-3">
                            {standup.blockers.map((item, index) => (
                                <motion.div
                                    key={item.key}
                                    initial={{ opacity: 0, x: -20 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: index * 0.1 + 0.4 }}
                                    className="p-4 rounded-xl bg-danger/10 border border-danger/20"
                                >
                                    <div className="flex items-center gap-4">
                                        <AlertCircle className="w-5 h-5 text-danger" />
                                        <span className="text-accent font-mono text-sm">{item.key}</span>
                                        <span className="flex-1">{item.title}</span>
                                        <span className="badge-danger">{item.days} days blocked</span>
                                    </div>
                                    <p className="mt-2 text-text-muted text-sm pl-9">
                                        Reason: {item.reason}
                                    </p>
                                </motion.div>
                            ))}
                        </div>
                    )}
                </div>
            </motion.div>

            {/* Actions */}
            <motion.div variants={itemVariants} className="flex justify-center gap-4">
                <button className="btn-secondary">
                    <Send className="w-4 h-4 mr-2" />
                    Send to Slack
                </button>
                <button className="btn-secondary">
                    <MessageSquare className="w-4 h-4 mr-2" />
                    Post to Confluence
                </button>
            </motion.div>
        </motion.div>
    )
}
